### ISSUE TITLE
Very high sidebar scrolls, but not fixed

### ISSUE THREAD

**Issue by burateen** [emn178/jquery-stickit#13]
Hello!
Please, look at http://www.revda-info.ru/
Right sidebar very high relative to the screen, there are a lot of elements. Advertisement (first block) is not fixed and goes up. What am I doing wrong? Or so it runs by default?

**Comment by emn178** [comment]
Hi,

This is a feature added by #8. When the sticky element higher than the screen, it will keep scrolling until bottom or top of element. Otherwise, the users can not see the bottom part of the element until end. 

The other thing is that you have fixed header on the top, so you should set the option "top", in your case {top:113}. Or it will stick the top position behind the header.

I can add a option to disable the scrolling feature in next feature.

**Comment by burateen** [comment]
> I can add a option to disable the scrolling feature in next feature.
Add please

**Comment by emn178** [comment]
Hi,

I added a feature to disable scrolling in 0.2.3.
You can set `overflowScrolling` false to do this now.
